name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21


      - name: Install dependencies
        run: |
          go mod download

      - name: Run Go Vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

  publish:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.Username }}
          password: ${{ secrets.token }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: .  
    
      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .  
          push: true
          tags: anburbaeva/fff:${{ github.sha }}
          labels: org.opencontainers.image.created=${{ github.run_at }}